export const FETCH_COLLEGES_START = 'FETCH_COLLEGES_START';
export const FETCH_COLLEGES_SUCCESS = 'FETCH_COLLEGES_SUCCESS';
export const FETCH_COLLEGES_FAIL = 'FETCH_COLLEGES_FAIL';

export const FETCH_STUDENTS_START = 'FETCH_STUDENTS_START';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAIL = 'FETCH_STUDENTS_FAIL';

export const FETCH_CHARTS_START = 'FETCH_CHARTS_START';
export const FETCH_CHARTS_SUCCESS = 'FETCH_CHARTS_SUCCESS';
export const FETCH_CHARTS_FAIL = 'FETCH_CHARTS_FAIL';
